version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    volumes:
      - ./back/src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 80:80

  web:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 9999:8080
    volumes:
      - ./front/src/:/app
    stdin_open: true
    tty: true
  
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - 33062:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      